### ISSUE TITLE
How i can use it with endpoint?

### ISSUE THREAD

**Issue by KeST3107** [benyblack/rest-mock-core#10]
Can you say something for this?

**Comment by benyblack** [comment]
Can you explain it a bit more or give me an example?

**Comment by KeST3107** [comment]
```
public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            var server = new HttpServer();
            server.Configure();
            server.Run();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context => { await context.Response.WriteAsync("Hello World!"); });
            });
        }
    }
```

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5002
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\kn.sumarokov\RiderProjects\WebRestMock\WebRestMock
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

How can I make the service run on port 5002 and start when the application starts?

**Comment by benyblack** [comment]
If you want to run it as a server on a specific port you can do like this:
```csharp
HttpServer mockServer = new HttpServer(5002);
mockServer.Run();
```
About endpoints, I don't see any benefits there. The goal of this project is to have a simple mock http server.
The example you sent can be done by simply config the server like this:
```csharp
mockServer.Config.Get("/").Send("Hello World!");
```
