### ISSUE TITLE
mockServer is throwing an exception on Run

### ISSUE THREAD

**Issue by RetroCoder** [benyblack/rest-mock-core#2]
When I call “Run” on the mockServer it throws an exception: Could not load type 'Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions' from assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I am using .netcore v2 under Visual Studio 2017

**Comment by benyblack** [comment]
Please check if the error is fixed. There were several issues because of migration to .net core 2.0.
I've fixed them and the NuGet package is updated.
